In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [30]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [35]:
np.sum(a,axis=1,keepdims=True)

array([[ 6],
       [15]])

In [25]:
db = np.sum(a, axis=0, keepdims=False)
db.shape

(3,)

In [27]:
ans=np.random.randn(3)
ans.shape

(3,)

In [28]:
ans[1]

-0.7181891876775855

In [21]:
a=np.concatenate([a,np.ones((a.shape[0],1))],axis=-1)
a

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.]])

In [18]:
sum(a[0,:]*b[0,:])

50

In [13]:
a.shape[0]

2

In [15]:
np.random.randn(3,2)

array([[ 0.02761446, -2.11771806],
       [ 0.96045472,  0.39904967],
       [-0.44951921,  1.33409684]])

In [14]:
out=a.reshape(2, -1)
out.shape

(2, 3)

In [4]:
a[0:1,0:1]

array([[1]])

In [5]:
b[0:2,0:2]

array([[ 7,  8],
       [10, 11]])

In [3]:
a[0:1,0:1]*b[0:2,0:2]

array([[ 7,  8],
       [10, 11]])